export const activityData = [
	{
		id: 1,
		owner: 'Lauri Dagostino',
		action: 'added',
		target: 'Mackenzie Dagostino',
		description: 'as a co-owner to',
		eventName: 'Event #1!',
		date: 'Today',
	},
	{
		id: 2,
		owner: 'You',
		action: 'updated',
		target: 'Ticket Settings',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-02-01',
	},
	{
		id: 3,
		owner: 'Ticket Price Changed',
		action: 'by',
		target: 'Schedule',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-03-01',
	},
	{
		id: 4,
		owner: 'Team Roster Locked',
		action: 'by',
		target: 'Schedule',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-04-01',
	},
	{
		id: 5,
		name: 'You sent Emails to All Club Directors for Big Event 2024.',
		owner: 'You',
		action: 'sent',
		target: 'Emails',
		description: 'to',
		eventName: 'All Club Directors for Big Event 2024.',
		date: '2022-05-01',
	},
	{
		id: 6,
		owner: 'Lauri Dagostino',
		action: 'added',
		target: 'Mackenzie Dagostino',
		description: 'as a co-owner to',
		eventName: 'Event #1!',
		date: '2022-05-01',
	},
	{
		id: 7,
		owner: 'You',
		action: 'updated',
		target: 'Ticket Settings',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-02-01',
	},
	{
		id: 8,
		owner: 'Ticket Price Changed',
		action: 'by',
		target: 'Schedule',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-03-01',
	},
	{
		id: 9,
		owner: 'Team Roster Locked',
		action: 'by',
		target: 'Schedule',
		description: 'in',
		eventName: 'Big Event 2024.',
		date: '2022-04-01',
	},
	{
		id: 10,
		name: 'You sent Emails to All Club Directors for Big Event 2024.',
		owner: 'You',
		action: 'sent',
		target: 'Emails',
		description: 'to',
		eventName: 'All Club Directors for Big Event 2024.',
		date: '2022-05-01',
	},
];
